export const ADD_EDIT_PRODUCT_NAME = 'ADD_EDIT_PRODUCT_NAME';
export const ADD_EDIT_PRODUCT_DESCRIPTION = 'ADD_EDIT_PRODUCT_DESCRIPTION';
export const ADD_PRODUCT_VARIETY = 'ADD_PRODUCT_VARIETY';
export const EDIT_PRODUCT_VARIETY = 'EDIT_PRODUCT_VARIETY';
export const REMOVE_PRODUCT_VARIETY = 'REMOVE_PRODUCT_VARIETY';
